### ISSUE TITLE
Das Literaturverzeichnis wird nicht angezeigt.

### ISSUE THREAD

**Issue by ghost** [a-leithner/latex-vwa-template#1]
Obwohl der Befehl \printbibliography verwendet wird und einzelne Zitate als solche erkannt werden und in die Fußzeile gesetzt werden, wird kein Literaturverzeichnis erstellt. Kann man da etwas machen, um das Literaturverzeichnis angezeigt zu bekommen?

**Comment by a-leithner** [comment]
Das ist sehr seltsam. Normalerweise (und ich verwende diese Vorlage, so wie sie ist, selbst) sollte das Literaturverzeichnis erstellt werden, wenn die Quellen richtig in den Fußzeilen platziert werden. U.U. muss LaTeX wie gezeigt nach Biber zweimal aufgerufen werden, damit es das Literaturverzeichnis auch ins Dokument schafft. Gibt es irgendwelche Warnungen beim Kompilieren des Dokuments mit LaTeX? Wie wird das Dokument denn erstellt (über die Kommandozeile oder über einen Editor, wie TeXShop o.ä.)?

**Comment by ghost** [comment]
Ich arbeite zurzeit mit Texmaker und die einzig relevanten Warnung wären:
"Empty bibliography", "citation XY on page x not defined" (obwohl dieses Zitat definiert ist und auch in den Kapiteldatein in der Fußzeile angezeigt werden), "Please (re)run Biber on the file"
Ich weiß leider nicht was man nun machen muss bzw. soll.

**Comment by a-leithner** [comment]
Ich arbeite leider nicht mit TeXMaker, weshalb ich da keine Anweisungen geben kann. Dass allerdings „Please (re)run Biber on the file...“ angezeigt wird, ist ein Hinweis darauf, dass die Kompilierung („Erzeugung“ des PDF) nicht korrekt eingestellt ist. [Hier](https://texwelt.de/fragen/1909/wie-verwende-ich-biber-in-meinem-editor?Seite=1&focusedAnswerId=16701#16701) findet sich eine kurze Anleitung, wo man Biber wohl hinterlegen muss. Nach dem ersten Erstellen des PDFs muss man dann Biber ausführen (wie dort steht mittels Drücken der F11-Taste) und dann noch zweimal ganz normal das PDF erzeugen lassen. Wichtig ist, dass Biber immer ausgeführt werden muss, wenn man neue Quellen hinzufügt!

Alternativ kann das Ganze auch über die Kommandozeile (unter Windows „Eingabeaufforderung“) gemacht werden. Wie das geht, steht aber in der [README.md](../).
